# Generated by Django 5.1.3 on 2024-11-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_size", models.CharField(max_length=100)),
                ("destruction_level", models.CharField(max_length=100)),
                ("gps", models.CharField(max_length=100)),
            ],
        ),
    ]
