# Generated by Django 5.1.3 on 2024-11-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroneSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_lat", models.FloatField()),
                ("starting_lon", models.FloatField()),
                ("speed_kmh", models.FloatField()),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("N", "North"),
                            ("NE", "North-East"),
                            ("E", "East"),
                            ("SE", "South-East"),
                            ("S", "South"),
                            ("SW", "South-West"),
                            ("W", "West"),
                            ("NW", "North-West"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
