# Generated by Django 5.1.3 on 2024-11-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_dronesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListData",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("time", models.FloatField()),
                ("class_name", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=100)),
            ],
        ),
    ]
